### PR TITLE
Rename lint unused_doc_comment to unused_doc_comments

### PR DESCRIPTION
**Pull request by hoodie**

### CODE REVIEW

**Comment by df5602** [comment]
@bjgill Won't this still generate the same warnings that prompted this pull request? (see issue #245 )

**Comment by bjgill** [comment]
Good point - we also need to allow `renamed_and_removed_lints`. I've done that in https://github.com/bjgill/error-chain/tree/lint-problem, which compiles without warnings in both stable and nightly (c.f. this PR, which has warnings ins stable, and master, which has warnings in nightly).

@hoodie - do you want to take on my back-compatibility enhancement (or equivalent)? Otherwise, I'll open a new PR tomorrow.

**Comment by TedDriggs** [comment]
What are the cases that generate unused doc comments? If we can fix those, then we can remove the lint outright, and have no version compatibility concerns.

**Comment by bjgill** [comment]
I believe the problem is https://github.com/rust-lang-nursery/error-chain/issues/63 (attribute handling in `links`)

**Comment by Yamakaky** [comment]
Closing for #247

**Pull request closed without merging**
