### PR TITLE
Remove `unknown_lints` warning on stable

### LINKED ISSUE #208: error-chain currently produces `unknown lint` warning on stable
e.g. (from https://travis-ci.org/rust-lang-nursery/error-chain/jobs/259646671):

```
warning: unknown lint: `unused_doc_comment`
   --> tests/tests.rs:621:5
    |
621 | /     error_chain! {
622 | |         links { }
623 | |
624 | |         foreign_links { }
...   |
631 | |         }
632 | |     };
    | |______^
    |
    = note: #[warn(unknown_lints)] on by default
    = note: this error originates in a macro outside of the current crate
```

This seems to be due to `unused_doc_comment` being a new warning that's present in nightly only.

Would it be worth adding `#[allow(unknown_lints)]` to some of the macros?

### PR DESCRIPTION
**Pull request by BenjaminGill-Metaswitch**
And deny warnings in CI

Fixes #208

### CODE REVIEW

**Comment by Yamakaky** [comment]
Oh, right, good!

**Comment by BenjaminGill-Metaswitch** [comment]
Thanks. Any chance this could get published as 0.11.0-rc.3?

**Comment by Yamakaky** [comment]
#162 will probably be merged soon so I'm waiting for that.

**Comment by BenjaminGill-Metaswitch** [comment]
OK. Thanks.

**Comment by BenjaminGill-Metaswitch** [comment]
Sorry - any progress?

**Pull request merged**
