### PR TITLE
src: Remove executable bit from source files

### PR DESCRIPTION
**Pull request by cgwalters**
I know this seems silly, but RPM builds of
https://github.com/coreos/coreos-installer/
are failing for me because RPM sticks these source files in
"debugsource" directories, and then a "linter" check notices
they appear to be executable but lack a shebang `#!` line.

There's no reason for source to be directly executable,
so remove that bit.

### CODE REVIEW

**Comment by bgilbert** [comment]
Commit 542c12c8a1683df6898f73ce64e6534c96c8a9c9 reinstated the execute bit on `lib.rs` (and, indeed, every other file it touched).

**Comment by AndyGauge** [comment]
Perfect!  glad to hear we’ve regressed.

**Comment by cgwalters** [comment]
Andy, what's the `umask` value on your system?  Is your editor creating files with the executable bit by default for some reason?

**Comment by AndyGauge** [comment]
I'm using windows subsystem for linux on the machine I just released from.  The file system that holds the files is NTFS and the file system adapter ends up causing these problems.  
I'll be releasing 0.12.4 with a mac to avoid the problem.

**Comment by AndyGauge** [comment]
OK, I've published 0.12.4 to address this problem.  I'll try to be more cognizant of the file permissions on all of the codebases I touch because of this, but I do apologize for this learning experience impacting other's workflow.

**Pull request merged**
