### PR TITLE
Add ResultExt::from_err() wrt #119

### PR DESCRIPTION
**Pull request by hasufell**
Is that ok? The macros are so complex I don't really know. But it compiles and works in my own project as expected. Also, didn't add any tests.

### CODE REVIEW

**Comment by bennyyip** [comment]
I like this PR, should we merge it?

**Comment by Yamakaky** [comment]
I don't really like the method name. Maybe something like `convert` or `convert_error`?

**Comment by hasufell** [comment]
I have no strong opinion on the function name. This is just the best I could come up with.

**Comment by Yamakaky** [comment]
There is a lot of `_err` in std (`Result::err`, `unwrap_err`, `is_err`), so I think `convert_err` would be appropriate.

**Comment by Yamakaky** [comment]
Also, could you update the changelog, add a test and update the doc/examples ?

**Comment by bennyyip** [comment]
@Yamakaky `futures` use `from_err` too, maybe follow this name is easier to understand.
https://docs.rs/futures/0.1.14/futures/future/trait.Future.html#method.from_err.

**Comment by Yamakaky** [comment]
Right!

**Comment by hasufell** [comment]
I tried to rebase this patch against master, but the addition of `Option` impl broke this patch.

**Comment by hasufell** [comment]
Abandoning.

**Pull request closed without merging**
